# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sopt-27th-HACKATHON-6th' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sopt-27th-HACKATHON-6th
  pod 'Kingfisher', '~> 5.0' 
  pod 'SwiftyJSON','~>4.0'  
  pod 'Alamofire', '~> 5.1'
  pod 'lottie-ios' 
  pod 'KakaoSDKLink' # 메시지(카카오링크)
  pod 'KakaoSDKTemplate' # 메시지 템플릿 
  pod 'KakaoSDKCommon'  
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'KakaoSDKUser'  # 사용자 관리
  pod 'NVActivityIndicatorView'
end
