# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT-27th-HACKATHON' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT-27th-HACKATHON
  pod 'Kingfisher', '~> 5.0' 
  pod 'SwiftyJSON','~>4.0'  
  pod 'Alamofire', '~> 5.1'
  pod 'lottie-ios' 


end
